### ISSUE TITLE
HTML broken from internal CSS

### ISSUE THREAD

**Issue by April6804** [lpowell0066/Nikis-Top-10-Mix#4]
https://github.com/lpowell0066/Nikis-Top-10-Mix/blob/e29983ccf22952ef8df4ac2f0b698f58b4f6c739/index.html#L7

Take out line 7-9 so your HTML can be seen on the webpage.

**Comment by lpowell0066** [comment]
okay i was like what did i do wrong she made it look so easy im gonna finish working on it today thanks!
________________________________
